# ---------------------------------------------------------------------------------------------------------------------
# Generic Azure CI/CD Pipeline kickstart for Powershell ModuleBuilder Modules.
#
# IMPORTANT: requires installing the https://marketplace.visualstudio.com/items?itemName=gittools.gitversion task
#            into your Azure Devops organization (`Get it free` button)
#
# TODO:
# - check all template parameters
# - step-by-step instructions (enable github, new devops project, install task, etc)
# ---------------------------------------------------------------------------------------------------------------------

name: $(GitVersion_InformationalVersion)

trigger:
- master

variables:
  ArtifactName: Modules

stages:
- stage: Build
  jobs:
  - template: .azure-templates/jobs/initialize.yml
  - template: .azure-templates/jobs/gitversion.yml
  - template: .azure-templates/jobs/build-module.yml
    parameters:
      dependsOn: [Gitversion]
      artifactName: $(ArtifactName)

- stage: Validate
  dependsOn: Build
  jobs:
  - template: .azure-templates/jobs/script-analyzer.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)

  - template: .azure-templates/jobs/pester.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests' # Linux users: be aware of the upperase
      strategy:
        matrix:
          # Linux:
          #   vmImage: 'ubuntu-16.04'
          # MacOS:
          #   vmImage: 'macOS-10.14'
          Windows:
            vmImage: 'windows-2019'
      pool:
        vmImage: $(vmImage)


# ---------------------------------------------------------------------------
# Publish module to PSGallery and create Github Release
#
# IMPORTANT: skipped if not on master AND/OR [no-release] in the commit.
# ---------------------------------------------------------------------------
- stage: Publish
  dependsOn: Validate
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  jobs:
  - template: .azure-templates/jobs/psgallery-publish-module.yml
    parameters:
      artifactName: $(ArtifactName)

  # job: commit new manifest als [no-release] chore

  # https://developer.github.com/v3/repos/releases/#create-a-release
  - template: .azure-templates/jobs/github-create-release.yml
    parameters:
      dependsOn: ['PSGallery']
      artifactName: $(ArtifactName)
      githubName: 'alt3'
      githubRepo: 'Docusaurus.Powershell'
