# ---------------------------------------------------------------------------------------------------------------------
# Generic Azure CI/CD Pipeline kickstart for Powershell ModuleBuilder Modules.
#
# IMPORTANT: requires installing the https://marketplace.visualstudio.com/items?itemName=gittools.gitversion task
#            into your Azure Devops organization (`Get it free` button)
#
# TODO:
# - check all template parameters
# - step-by-step instructions (enable github, new devops project, install task, etc)
# ---------------------------------------------------------------------------------------------------------------------

name: $(GitVersion_InformationalVersion)

trigger:
- master

variables:
  ArtifactName: Modules

stages:
- stage: Build
  jobs:
  - template: .azure-templates/jobs/initialize.yml
  - template: .azure-templates/jobs/gitversion.yml
  - template: .azure-templates/jobs/build-module.yml
    parameters:
      dependsOn: [Gitversion]
      artifactName: $(ArtifactName)

- stage: Validate
  dependsOn: Build
  jobs:
  - template: .azure-templates/jobs/script-analyzer.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)

  - template: .azure-templates/jobs/pester.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests' # Linux users: be aware of the upperase
      strategy:
        matrix:
          Linux:
            vmImage: 'ubuntu-16.04'
          MacOS:
            vmImage: 'macOS-10.14'
          Windows:
            vmImage: 'windows-2019'
      pool:
        vmImage: $(vmImage)
